In [79]:
import pandas as pd
import numpy as np
import json
import math

In [99]:
#считываем данные 
data=pd.read_csv('data.csv')
day=pd.read_csv('context_day.csv')
place=pd.read_csv('context_place.csv')
data

,Unnamed: 0,Movie 1,Movie 2,Movie 3,Movie 4,Movie 5,Movie 6,Movie 7,Movie 8,Movie 9,...,Movie 21,Movie 22,Movie 23,Movie 24,Movie 25,Movie 26,Movie 27,Movie 28,Movie 29,Movie 30
0,User 1,-1,4,1,5,-1,-1,-1,1,3,...,2,4,-1,-1,3,4,-1,2,4,1
1,User 2,4,5,2,3,3,4,-1,5,3,...,-1,2,-1,3,1,5,-1,5,2,2
2,User 3,4,2,5,4,1,5,-1,3,5,...,4,-1,5,4,5,1,2,1,-1,3
3,User 4,5,-1,2,-1,-1,2,4,3,2,...,-1,2,2,2,2,5,3,2,5,5
4,User 5,4,3,3,3,5,3,3,4,5,...,4,5,2,-1,3,5,1,-1,5,-1
5,User 6,2,-1,3,3,3,3,4,2,-1,...,5,-1,1,3,-1,4,4,5,1,2
6,User 7,4,1,4,4,1,4,5,2,2,...,2,5,1,3,4,-1,4,3,1,4
7,User 8,-1,5,5,3,3,3,3,3,1,...,-1,3,1,3,2,1,4,-1,1,3
8,User 9,1,2,3,1,5,3,3,1,2,...,3,2,3,-1,1,4,3,1,5,3
9,User 10,5,-1,1,-1,3,3,4,1,1,...,4,1,4,1,4,5,2,3,-1,1
10,User 11,-1,5,-1,1,5,2,4,2,4,...,4,-1,3,4,1,2,4,2,5,1
11,User 12,5,4,4,-1,3,-1,5,5,5,...,1,4,1,5,3,5,4,3,5,5
12,User 13,1,1,4,5,4,3,5,5,5,...,2,3,2,-1,4,3,-1,5,5,4
13,User 14,3,5,4,-1,1,2,4,-1,-1,...,4,1,5,4,1,-1,3,1,5,3
14,User 15,3,5,3,4,4,-1,4,4,2,...,2,2,5,1,3,4,-1,-1,5,4
15,User 16,3,3,5,3,2,2,5,-1,4,...,1,3,4,-1,4,4,4,2,4,4
16,User 17,1,1,-1,-1,4,4,-1,-1,1,...,4,2,4,2,2,-1,5,4,5,3
17,User 18,4,3,3,2,1,5,3,4,5,...,-1,4,5,2,1,1,2,1,-1,4
18,User 19,4,3,5,5,4,4,-1,-1,4,...,2,3,1,2,-1,2,5,1,2,1
19,User 20,2,-1,2,5,-1,-1,1,-1,2,...,-1,2,4,1,-1,2,2,3,3,4
20,User 21,-1,2,1,2,3,5,4,1,2,...,-1,5,1,2,5,5,4,4,2,-1
21,User 22,2,4,4,-1,4,-1,4,5,5,...,4,5,1,-1,-1,5,2,2,5,-1
22,User 23,5,1,-1,5,5,-1,-1,5,-1,...,-1,-1,3,1,5,-1,1,5,3,5
23,User 24,5,4,2,-1,2,1,3,2,1,...,4,2,2,1,3,2,5,2,5,4
24,User 25,3,1,-1,4,2,-1,4,1,5,...,2,-1,5,5,2,-1,1,3,1,2
25,User 26,1,5,-1,3,-1,2,4,-1,4,...,5,3,1,5,2,-1,2,2,4,-1
26,User 27,4,4,3,-1,4,5,3,4,3,...,-1,3,4,3,-1,3,2,3,2,5
27,User 28,-1,-1,4,2,3,2,1,4,-1,...,1,3,2,1,4,3,2,4,2,1
28,User 29,3,2,4,2,2,2,4,1,3,...,3,-1,3,5,5,5,4,-1,5,-1
29,User 30,2,3,5,4,1,3,3,2,3,...,4,5,1,1,4,5,3,1,3,5
30,User 31,3,5,4,5,1,3,3,3,4,...,5,4,4,3,5,2,2,4,4,-1
31,User 32,5,4,5,4,1,5,5,4,4,...,5,2,-1,2,3,2,1,3,1,-1
32,User 33,5,3,4,4,2,1,3,1,3,...,2,1,5,5,2,-1,2,1,4,2
33,User 34,-1,5,-1,-1,1,-1,5,1,1,...,3,3,4,-1,3,1,5,2,2,5
34,User 35,4,-1,5,4,2,2,3,1,1,...,5,1,2,1,5,5,1,-1,5,5
35,User 36,3,2,-1,5,5,1,5,2,1,...,-1,2,4,3,4,5,2,1,3,4
36,User 37,-1,4,-1,3,1,4,5,4,3,...,3,3,-1,5,-1,5,2,3,5,-1
37,User 38,3,-1,1,4,2,3,4,-1,5,...,5,4,3,-1,1,4,3,-1,-1,4
38,User 39,1,-1,5,-1,1,2,3,-1,2,...,4,2,5,2,3,1,2,1,2,1
39,User 40,-1,1,1,1,1,-1,4,1,-1,...,3,5,4,2,3,4,5,5,3,2

In [81]:
#выбираем пользователя для расчета
variant = 38
userID= variant - 1
data.iloc[userID]

Unnamed: 0    User 38
 Movie 1            3
 Movie 2           -1
 Movie 3            1
 Movie 4            4
 Movie 5            2
 Movie 6            3
 Movie 7            4
 Movie 8           -1
 Movie 9            5
 Movie 10           3
 Movie 11           3
 Movie 12          -1
 Movie 13           3
 Movie 14           2
 Movie 15           4
 Movie 16           3
 Movie 17           1
 Movie 18           4
 Movie 19           2
 Movie 20           1
 Movie 21           5
 Movie 22           4
 Movie 23           3
 Movie 24          -1
 Movie 25           1
 Movie 26           4
 Movie 27           3
 Movie 28          -1
 Movie 29          -1
 Movie 30           4
Name: 37, dtype: object

In [85]:
#удаляем стоблбец с именами пользователей
data = data.drop(data.columns[0], axis = 1)

In [86]:
#находим метрику сходства с каждым пользователем
def sim(v):
    resultList = {}
    for u in range(data.shape[0]):
        num = 0
        vdenum = 0
        udenum = 0
        if (u != v):        
            uv = data.iloc[[u, v]]
            uv = uv.transpose()
            for i,movie in uv.iterrows():
                if ((movie[u] != -1) & (movie[v] != -1 )):
                    num += movie[u] * movie[v]
                    udenum += pow(movie[u], 2)
                    vdenum += pow(movie[v], 2)
                    res = round(num / ((math.sqrt(udenum) * math.sqrt(vdenum))), 3)
        resultList[u] = res
        #сортируем результат и выбираем четырех ближайших соседей
        sim = list(resultList.items())
        sim.sort(key = lambda i: i[1], reverse = True)
        sim = sim[:4]
    return sim

In [87]:
simk = sim(userID)
simk

[(25, 0.932), (21, 0.924), (5, 0.915), (11, 0.91)]

In [88]:
#функция для поиска средней оценки пользователя
def avg(user):
    count = 0
    mark = 0
    for i in range(1, data.shape[1]):
        if data.iloc[user][i] != -1:
            count += 1
            mark += data.iloc[user][i]
    res = round(mark/count,3)
    return res

In [89]:
avg(userID)

3.0

In [90]:
#с помощью метрики косинуса находим предполагаемую оценку пользователя для фильма
def getMark(u, movie):
    num = 0
    denum = 0
    if data.iloc[u, movie] == -1:
        for v in simk:
                if data.iloc[v[0], movie] != -1:
                    num += v[1]*(data.iloc[v[0], movie]-avg(v[0]))
                    denum += v[1] 
        res = round(avg(u)+num/denum, 3)
    return res

In [101]:
#получаем результат для всех неоцененных фильмов
def firstRes():
    result = []
    for i in range(data.shape[1]):
        if data.iloc[userID, i] == -1:
            result.append("Movie "+str(i)+": "+ str(getMark(userID, i)))
    return result

In [102]:
firstRes()

['Movie 2: 4.013',
 'Movie 8: 3.595',
 'Movie 12: 3.204',
 'Movie 24: 4.031',
 'Movie 28: 2.71',
 'Movie 29: 3.469']

In [103]:
for i in range(data.shape[1]):
    if data.iloc[userID,i] == -1:
        print(i)

2
8
12
24
28
29

In [104]:
#записываем результат в файл
def writeJson(uderID, firstTask, fileName='result.json'):
    result = {"user": variant,
              "1": firstTask,
              }
    with open(fileName, 'w') as f:
        json.dump(result, f, indent=10)

In [105]:
writeJson(userID, firstRes())